### ISSUE TITLE
parallel pool shutdown due to error

### ISSUE THREAD

**Issue by awong26** [atdemarco/svrlsmgui#2]
There is a problem that happens occasionally when trying to run this script in parallel mode, when the parallel pool shuts down due to an error during step 1. It's unclear exactly what the error is, because the error that shows up in the command window is that fetchNext is trying to access a non-existent worker (likely because this call to fetchNext probably happens after the real error occurred and the parallel pool was shut down).

**Comment by atdemarco** [comment]
Sorry for the delay in responding here, have you noticed any patterns to this error? Does it reliably happen when running the same analysis? Or does it seem random?

**Comment by awong26** [comment]
I switched over to running this on the Mac, and haven't had any problems. I never worked through exactly why I was having trouble on my PC.
