### ISSUE TITLE
Attempt to execute SCRIPT RunAnalysis as a function

### ISSUE THREAD

**Issue by fissell** [atdemarco/svrlsmgui#3]
Hi,

We installed svrlsmgui and when we hit the 'Run Analysis' we get the error:

>> Attempt to execute SCRIPT RunAnalysis as a function:
/home/fissell/Volumes/FiezData/Ortho/dyslexia/NiiStat/SVRLSM/svrlsmgui-master/functions/RunAnalysis.m

Error in svrlsmgui>runanalysisbutton_Callback (line 634)
    [success,handles] = RunAnalysis(hObject,eventdata,handles); % now returns handles 10/26/17

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in svrlsmgui (line 40)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)svrlsmgui('runanalysisbutton_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

We also get a warning "Cannot load an object of class 'AxesToolbar'" when we launch the gui, but I don't think that's causing the script/function error.

We are running matlab R2017a on an Ubuntu Linux system.

Any help you can give would be much appreciated.

thanks
Kate

**Comment by atdemarco** [comment]
For the RunAnalysis error, you usually see this error when an .m file of the same name is higher on the path and has the same name as the one you want to execute. See if this is the case by typing "which -all RunAnalysis"

The AxesToolbar message is, as you suspect, a harmless warning. It is related to the MATLAB version you're running, specifically that the GUI was created in a newer version of MATLAB. It can be ignored.
